class_name ClassSkillData
extends RefCounted

## Vanilla 1.12 DATA-003; see docs/data/renaissance.md.
const CLASSES: Array[StringName] = [&"Mage", &"Druid", &"Warlock", &"Priest", &"Shaman", &"Paladin"]
const RANKS: Dictionary = {
	"devotion_aura_1": {
		"title": "Devotion Aura",
		"class_tab": "Paladin",
		"source_id": 465,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 0,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 9,
		"family": "devotion_aura",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 55,
		"maximum": 55,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Toggle a 6-tile party armor aura; one aura at a time. Costs one turn."
	},
	"holy_light_1": {
		"title": "Holy Light",
		"class_tab": "Paladin",
		"source_id": 635,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 35,
		"mana_percent": 0,
		"cast_seconds": 2.5,
		"range_tiles": 8,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 5,
		"family": "holy_light",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 39,
		"maximum": 47,
		"scaling_rate": 0.8,
		"coefficient": 0.205357,
		"detail": ""
	},
	"seal_of_righteousness_1": {
		"title": "Seal of Righteousness",
		"class_tab": "Paladin",
		"source_id": 21084,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 20,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 30,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 7,
		"family": "seal_of_righteousness",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 108,
		"maximum": 108,
		"scaling_rate": 18,
		"coefficient": 0,
		"detail": "Adds holy damage on landed melee hits for 30 turns. Judgement consumes the seal."
	},
	"blessing_of_might_1": {
		"title": "Blessing of Might",
		"class_tab": "Paladin",
		"source_id": 19740,
		"rank": 1,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 20,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 300,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "blessing_of_might",
		"effect": "ARMOR",
		"target": "ALLY",
		"minimum": 20,
		"maximum": 20,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Adds 20 attack power for 300 turns; one blessing per target."
	},
	"judgement_1": {
		"title": "Judgement",
		"class_tab": "Paladin",
		"source_id": 20271,
		"rank": 1,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 0,
		"mana_percent": 6,
		"cast_seconds": 1.0,
		"range_tiles": 2,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 10,
		"scaling_max": 0,
		"family": "judgement",
		"effect": "JUDGEMENT",
		"target": "ENEMY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Consume the active seal to judge an enemy. No GCD or turn cost; 10-turn cooldown.",
		"free_instant": true
	},
	"divine_protection_1": {
		"title": "Divine Protection",
		"class_tab": "Paladin",
		"source_id": 498,
		"rank": 1,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 15,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 6,
		"school": 1,
		"cooldown_seconds": 300,
		"scaling_max": 0,
		"family": "divine_protection",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Physical immunity for 6 turns; prevents melee. Applies 60-turn Forbearance."
	},
	"holy_light_2": {
		"title": "Holy Light",
		"class_tab": "Paladin",
		"source_id": 639,
		"rank": 2,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 60,
		"mana_percent": 0,
		"cast_seconds": 2.5,
		"range_tiles": 8,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 11,
		"family": "holy_light",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 76,
		"maximum": 90,
		"scaling_rate": 1.1,
		"coefficient": 0.339286,
		"prerequisite": "holy_light_1",
		"detail": ""
	},
	"seal_of_the_crusader_1": {
		"title": "Seal of the Crusader",
		"class_tab": "Paladin",
		"source_id": 21082,
		"rank": 1,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 30,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 12,
		"family": "seal_of_the_crusader",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 31,
		"maximum": 31,
		"scaling_rate": 0.7,
		"coefficient": 0,
		"detail": "Attack power and 40% faster swings with reduced weapon damage. Judgement increases holy damage taken."
	},
	"hammer_of_justice_1": {
		"title": "Hammer of Justice",
		"class_tab": "Paladin",
		"source_id": 853,
		"rank": 1,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 2,
		"duration": 3,
		"school": 1,
		"cooldown_seconds": 60,
		"scaling_max": 0,
		"family": "hammer_of_justice",
		"effect": "STUN",
		"target": "ENEMY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": ""
	},
	"purify_1": {
		"title": "Purify",
		"class_tab": "Paladin",
		"source_id": 1152,
		"rank": 1,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 0,
		"mana_percent": 8,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "purify",
		"effect": "PURIFY",
		"target": "ALLY",
		"minimum": 1,
		"maximum": 1,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Removes one poison and one disease from the selected ally."
	},
	"parry_1": {
		"title": "Parry",
		"class_tab": "Paladin",
		"source_id": 3127,
		"rank": 1,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 0,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 0,
		"school": 0,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "parry",
		"effect": "PASSIVE",
		"target": "NONE",
		"minimum": 1,
		"maximum": 6,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Passive: 5% frontal parry, retained across classes and Loops."
	},
	"lay_on_hands_1": {
		"title": "Lay on Hands",
		"class_tab": "Paladin",
		"source_id": 633,
		"rank": 1,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 0,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 8,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 3600,
		"scaling_max": 0,
		"family": "lay_on_hands",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"coefficient": 0.267857,
		"detail": "Heals for your maximum health; spends all current mana. 3600-turn cooldown."
	},
	"blessing_of_protection_1": {
		"title": "Blessing of Protection",
		"class_tab": "Paladin",
		"source_id": 1022,
		"rank": 1,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 6,
		"school": 1,
		"cooldown_seconds": 300,
		"scaling_max": 0,
		"family": "blessing_of_protection",
		"effect": "ARMOR",
		"target": "ALLY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Physical immunity for 6 turns; prevents melee. Applies 60-turn Forbearance."
	},
	"devotion_aura_2": {
		"title": "Devotion Aura",
		"class_tab": "Paladin",
		"source_id": 10290,
		"rank": 2,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 0,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 19,
		"family": "devotion_aura",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 160,
		"maximum": 160,
		"scaling_rate": 0,
		"coefficient": 0,
		"prerequisite": "devotion_aura_1",
		"detail": "Toggle a 6-tile party armor aura; one aura at a time. Costs one turn."
	},
	"seal_of_righteousness_2": {
		"title": "Seal of Righteousness",
		"class_tab": "Paladin",
		"source_id": 20287,
		"rank": 2,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 40,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 30,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 16,
		"family": "seal_of_righteousness",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 216,
		"maximum": 216,
		"scaling_rate": 17,
		"coefficient": 0,
		"prerequisite": "seal_of_righteousness_1",
		"detail": "Adds holy damage on landed melee hits for 30 turns. Judgement consumes the seal."
	},
	"smite_1": {
		"title": "Smite",
		"class_tab": "Priest",
		"source_id": 585,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 20,
		"mana_percent": 0,
		"cast_seconds": 1.5,
		"range_tiles": 6,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 6,
		"family": "smite",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 13,
		"maximum": 17,
		"scaling_rate": 0.5,
		"coefficient": 0.205275,
		"detail": ""
	},
	"power_word_fortitude_1": {
		"title": "Power Word: Fortitude",
		"class_tab": "Priest",
		"source_id": 1243,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 60,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 1800,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 10,
		"family": "power_word_fortitude",
		"effect": "ARMOR",
		"target": "ALLY",
		"minimum": 3,
		"maximum": 3,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "+3 stamina for 1800 turns."
	},
	"lesser_heal_1": {
		"title": "Lesser Heal",
		"class_tab": "Priest",
		"source_id": 2050,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 1.5,
		"range_tiles": 8,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 3,
		"family": "lesser_heal",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 46,
		"maximum": 56,
		"scaling_rate": 0.9,
		"coefficient": 0.123214,
		"detail": ""
	},
	"shadow_word_pain_1": {
		"title": "Shadow Word: Pain",
		"class_tab": "Priest",
		"source_id": 589,
		"rank": 1,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 18,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "shadow_word_pain",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"periodic_damage": 5,
		"tick_seconds": 3,
		"coefficient": 0,
		"tick_coefficient": 0.08,
		"detail": ""
	},
	"lesser_heal_2": {
		"title": "Lesser Heal",
		"class_tab": "Priest",
		"source_id": 2052,
		"rank": 2,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 45,
		"mana_percent": 0,
		"cast_seconds": 2.0,
		"range_tiles": 8,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 9,
		"family": "lesser_heal",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 71,
		"maximum": 85,
		"scaling_rate": 1.1,
		"coefficient": 0.228571,
		"prerequisite": "lesser_heal_1",
		"detail": ""
	},
	"power_word_shield_1": {
		"title": "Power Word: Shield",
		"class_tab": "Priest",
		"source_id": 17,
		"rank": 1,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 45,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 8,
		"duration": 30,
		"school": 1,
		"cooldown_seconds": 4,
		"scaling_max": 11,
		"family": "power_word_shield",
		"effect": "ARMOR",
		"target": "ALLY",
		"minimum": 44,
		"maximum": 44,
		"scaling_rate": 0.8,
		"coefficient": 0.0475,
		"detail": "Absorbs 44 damage for 30 turns; applies 15-turn Weakened Soul."
	},
	"smite_2": {
		"title": "Smite",
		"class_tab": "Priest",
		"source_id": 591,
		"rank": 2,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 2.0,
		"range_tiles": 6,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 11,
		"family": "smite",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 25,
		"maximum": 31,
		"scaling_rate": 0.6,
		"coefficient": 0.33915,
		"prerequisite": "smite_1",
		"detail": ""
	},
	"renew_1": {
		"title": "Renew",
		"class_tab": "Priest",
		"source_id": 139,
		"rank": 1,
		"training_level": 8,
		"training_cost": 200,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 8,
		"duration": 15,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 13,
		"family": "renew",
		"effect": "HEAL_OVER_TIME",
		"target": "ALLY",
		"minimum": 9,
		"maximum": 9,
		"scaling_rate": 0,
		"periodic_damage": 9,
		"tick_seconds": 3,
		"coefficient": 0,
		"tick_coefficient": 0.11,
		"detail": ""
	},
	"fade_1": {
		"title": "Fade",
		"class_tab": "Priest",
		"source_id": 586,
		"rank": 1,
		"training_level": 8,
		"training_cost": 200,
		"mana_cost": 40,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 10,
		"school": 5,
		"cooldown_seconds": 30,
		"scaling_max": 18,
		"family": "fade",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": -3,
		"coefficient": 0,
		"detail": "Temporarily reduces your threat by 55 for 10 turns; other engaged allies can take aggro."
	},
	"shadow_word_pain_2": {
		"title": "Shadow Word: Pain",
		"class_tab": "Priest",
		"source_id": 594,
		"rank": 2,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 50,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 18,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "shadow_word_pain",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"periodic_damage": 11,
		"tick_seconds": 3,
		"coefficient": 0,
		"tick_coefficient": 0.125,
		"prerequisite": "shadow_word_pain_1",
		"detail": ""
	},
	"resurrection_1": {
		"title": "Resurrection",
		"class_tab": "Priest",
		"source_id": 2006,
		"rank": 1,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 0,
		"mana_percent": 75,
		"cast_seconds": 10.0,
		"range_tiles": 6,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "resurrection",
		"effect": "RESURRECT",
		"target": "ALLY",
		"minimum": 70,
		"maximum": 70,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Out of combat: revive an ordinary friendly NPC at its unoccupied corpse with 70 health. Cannot revive the story guard or summons."
	},
	"lesser_heal_3": {
		"title": "Lesser Heal",
		"class_tab": "Priest",
		"source_id": 2053,
		"rank": 3,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 75,
		"mana_percent": 0,
		"cast_seconds": 2.5,
		"range_tiles": 8,
		"duration": 0,
		"school": 1,
		"cooldown_seconds": 0,
		"scaling_max": 15,
		"family": "lesser_heal",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 135,
		"maximum": 157,
		"scaling_rate": 1.6,
		"coefficient": 0.446429,
		"prerequisite": "lesser_heal_2",
		"detail": ""
	},
	"mind_blast_1": {
		"title": "Mind Blast",
		"class_tab": "Priest",
		"source_id": 8092,
		"rank": 1,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 50,
		"mana_percent": 0,
		"cast_seconds": 1.5,
		"range_tiles": 6,
		"duration": 0,
		"school": 5,
		"cooldown_seconds": 8,
		"scaling_max": 15,
		"family": "mind_blast",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 39,
		"maximum": 43,
		"scaling_rate": 0.6,
		"coefficient": 0.267857,
		"detail": ""
	},
	"healing_wave_1": {
		"title": "Healing Wave",
		"class_tab": "Shaman",
		"source_id": 331,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.5,
		"range_tiles": 8,
		"duration": 0,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 5,
		"family": "healing_wave",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 34,
		"maximum": 44,
		"scaling_rate": 0.7,
		"coefficient": 0.246416,
		"detail": ""
	},
	"lightning_bolt_1": {
		"title": "Lightning Bolt",
		"class_tab": "Shaman",
		"source_id": 403,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 15,
		"mana_percent": 0,
		"cast_seconds": 1.5,
		"range_tiles": 6,
		"duration": 0,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 6,
		"family": "lightning_bolt",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 13,
		"maximum": 15,
		"scaling_rate": 0.4,
		"coefficient": 0.205361,
		"detail": ""
	},
	"rockbiter_weapon_1": {
		"title": "Rockbiter Weapon",
		"class_tab": "Shaman",
		"source_id": 8017,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 15,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 300,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 6,
		"family": "rockbiter_weapon",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 1800,
		"maximum": 1800,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Main-hand enchant: +2 / +4 damage per second for 300 turns. One weapon enchant."
	},
	"earth_shock_1": {
		"title": "Earth Shock",
		"class_tab": "Shaman",
		"source_id": 8042,
		"rank": 1,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 4,
		"duration": 2,
		"school": 3,
		"cooldown_seconds": 6,
		"scaling_max": 9,
		"family": "earth_shock",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 17,
		"maximum": 19,
		"scaling_rate": 0.5,
		"coefficient": 0.15432,
		"detail": "Nature damage and a 2-turn school interrupt; shares Shock cooldown."
	},
	"stoneskin_totem_1": {
		"title": "Stoneskin Totem",
		"class_tab": "Shaman",
		"source_id": 8071,
		"rank": 1,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 120,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "stoneskin_totem",
		"effect": "SUMMON",
		"target": "NONE",
		"minimum": 5,
		"maximum": 5,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Earth: 5 health, 120 turns, 4-tile aura reducing melee damage by 4."
	},
	"healing_wave_2": {
		"title": "Healing Wave",
		"class_tab": "Shaman",
		"source_id": 332,
		"rank": 2,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 45,
		"mana_percent": 0,
		"cast_seconds": 2.0,
		"range_tiles": 8,
		"duration": 0,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 11,
		"family": "healing_wave",
		"effect": "HEAL",
		"target": "ALLY",
		"minimum": 64,
		"maximum": 78,
		"scaling_rate": 1,
		"coefficient": 0.407122,
		"prerequisite": "healing_wave_1",
		"detail": ""
	},
	"earthbind_totem_1": {
		"title": "Earthbind Totem",
		"class_tab": "Shaman",
		"source_id": 2484,
		"rank": 1,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 0,
		"mana_percent": 6,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 45,
		"school": 3,
		"cooldown_seconds": 15,
		"scaling_max": 0,
		"family": "earthbind_totem",
		"effect": "SUMMON",
		"target": "NONE",
		"minimum": 5,
		"maximum": 5,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Earth: 5 health, 45 turns, slows enemies 50% within 2 tiles."
	},
	"lightning_shield_1": {
		"title": "Lightning Shield",
		"class_tab": "Shaman",
		"source_id": 324,
		"rank": 1,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 45,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 600,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "lightning_shield",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 13,
		"maximum": 13,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Three 13-nature-damage charges over 600 turns; at most one discharge per 3 turns."
	},
	"lightning_bolt_2": {
		"title": "Lightning Bolt",
		"class_tab": "Shaman",
		"source_id": 529,
		"rank": 2,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 2.0,
		"range_tiles": 6,
		"duration": 0,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 13,
		"family": "lightning_bolt",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 26,
		"maximum": 30,
		"scaling_rate": 0.5,
		"coefficient": 0.392865,
		"prerequisite": "lightning_bolt_1",
		"detail": ""
	},
	"stoneclaw_totem_1": {
		"title": "Stoneclaw Totem",
		"class_tab": "Shaman",
		"source_id": 5730,
		"rank": 1,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 15,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 15,
		"school": 3,
		"cooldown_seconds": 30,
		"scaling_max": 0,
		"family": "stoneclaw_totem",
		"effect": "SUMMON",
		"target": "NONE",
		"minimum": 50,
		"maximum": 50,
		"scaling_rate": 3,
		"coefficient": 0,
		"detail": "Earth: 50 health, 15 turns; attracts enemies within 1 tile. 30-turn cooldown."
	},
	"rockbiter_weapon_2": {
		"title": "Rockbiter Weapon",
		"class_tab": "Shaman",
		"source_id": 8018,
		"rank": 2,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 300,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 14,
		"family": "rockbiter_weapon",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 1800,
		"maximum": 1800,
		"scaling_rate": 0,
		"coefficient": 0,
		"prerequisite": "rockbiter_weapon_1",
		"detail": "Main-hand enchant: +2 / +4 damage per second for 300 turns. One weapon enchant."
	},
	"earth_shock_2": {
		"title": "Earth Shock",
		"class_tab": "Shaman",
		"source_id": 8044,
		"rank": 2,
		"training_level": 8,
		"training_cost": 100,
		"mana_cost": 50,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 4,
		"duration": 2,
		"school": 3,
		"cooldown_seconds": 6,
		"scaling_max": 13,
		"family": "earth_shock",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 32,
		"maximum": 34,
		"scaling_rate": 0.7,
		"coefficient": 0.21219,
		"prerequisite": "earth_shock_1",
		"detail": "Nature damage and a 2-turn school interrupt; shares Shock cooldown."
	},
	"searing_totem_1": {
		"title": "Searing Totem",
		"class_tab": "Shaman",
		"source_id": 3599,
		"rank": 1,
		"training_level": 10,
		"training_cost": 400,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 30,
		"school": 2,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "searing_totem",
		"effect": "SUMMON",
		"target": "NONE",
		"minimum": 5,
		"maximum": 5,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Fire: 5 health, 30 turns; fires for 9\u201311 damage every 2.2 seconds within 4 tiles."
	},
	"flametongue_weapon_1": {
		"title": "Flametongue Weapon",
		"class_tab": "Shaman",
		"source_id": 8024,
		"rank": 1,
		"training_level": 10,
		"training_cost": 400,
		"mana_cost": 30,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 300,
		"school": 2,
		"cooldown_seconds": 0,
		"scaling_max": 16,
		"family": "flametongue_weapon",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 1800,
		"maximum": 1800,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Main-hand enchant: fire damage proportional to weapon speed on landed hits for 300 turns."
	},
	"flame_shock_1": {
		"title": "Flame Shock",
		"class_tab": "Shaman",
		"source_id": 8050,
		"rank": 1,
		"training_level": 10,
		"training_cost": 400,
		"mana_cost": 55,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 4,
		"duration": 12,
		"school": 2,
		"cooldown_seconds": 6,
		"scaling_max": 15,
		"family": "flame_shock",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 21,
		"maximum": 21,
		"scaling_rate": 0.8,
		"periodic_damage": 7,
		"tick_seconds": 3,
		"coefficient": 0.133875,
		"tick_coefficient": 0.0625,
		"detail": "Fire damage and a 12-turn burn; shares Shock cooldown."
	},
	"strength_of_earth_totem_1": {
		"title": "Strength of Earth Totem",
		"class_tab": "Shaman",
		"source_id": 8075,
		"rank": 1,
		"training_level": 10,
		"training_cost": 400,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 120,
		"school": 3,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "strength_of_earth_totem",
		"effect": "SUMMON",
		"target": "NONE",
		"minimum": 5,
		"maximum": 5,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Earth: 5 health, 120 turns; +10 strength within 4 tiles."
	},
	"immolate_1": {
		"title": "Immolate",
		"class_tab": "Warlock",
		"source_id": 348,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 2.0,
		"range_tiles": 6,
		"duration": 15,
		"school": 2,
		"cooldown_seconds": 0,
		"scaling_max": 5,
		"family": "immolate",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 8,
		"maximum": 8,
		"scaling_rate": 0.6,
		"periodic_damage": 4,
		"tick_seconds": 3,
		"coefficient": 0.0575,
		"tick_coefficient": 0.0575,
		"detail": ""
	},
	"shadow_bolt_1": {
		"title": "Shadow Bolt",
		"class_tab": "Warlock",
		"source_id": 686,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.7,
		"range_tiles": 6,
		"duration": 0,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 5,
		"family": "shadow_bolt",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 12,
		"maximum": 16,
		"scaling_rate": 0.4,
		"coefficient": 0.246416,
		"detail": ""
	},
	"demon_skin_1": {
		"title": "Demon Skin",
		"class_tab": "Warlock",
		"source_id": 687,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 50,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 1800,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "demon_skin",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 40,
		"maximum": 40,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Armor and +3 / +5 health every 5 turns, including combat."
	},
	"summon_imp_1": {
		"title": "Summon Imp",
		"class_tab": "Warlock",
		"source_id": 688,
		"rank": 1,
		"training_level": 1,
		"training_cost": 0,
		"mana_cost": 0,
		"mana_percent": 80,
		"cast_seconds": 10.0,
		"range_tiles": 0,
		"duration": 0,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "summon_imp",
		"effect": "SUMMON",
		"target": "NONE",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Summon one Imp on a free adjacent tile. Firebolt ranks at pet levels 1/8; Blood Pact at 4. Replaces your pet only on success."
	},
	"corruption_1": {
		"title": "Corruption",
		"class_tab": "Warlock",
		"source_id": 172,
		"rank": 1,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 35,
		"mana_percent": 0,
		"cast_seconds": 2.0,
		"range_tiles": 6,
		"duration": 12,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 9,
		"family": "corruption",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"periodic_damage": 10,
		"tick_seconds": 3,
		"coefficient": 0.0,
		"tick_coefficient": 0.0624,
		"detail": ""
	},
	"curse_of_weakness_1": {
		"title": "Curse of Weakness",
		"class_tab": "Warlock",
		"source_id": 702,
		"rank": 1,
		"training_level": 4,
		"training_cost": 100,
		"mana_cost": 20,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 120,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "curse_of_weakness",
		"effect": "CURSE",
		"target": "ENEMY",
		"minimum": 3,
		"maximum": 3,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Reduces physical damage by 3 for 120 turns. One warlock curse per target."
	},
	"shadow_bolt_2": {
		"title": "Shadow Bolt",
		"class_tab": "Warlock",
		"source_id": 695,
		"rank": 2,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 40,
		"mana_percent": 0,
		"cast_seconds": 2.2,
		"range_tiles": 6,
		"duration": 0,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 11,
		"family": "shadow_bolt",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 23,
		"maximum": 29,
		"scaling_rate": 0.6,
		"coefficient": 0.407122,
		"prerequisite": "shadow_bolt_1",
		"detail": ""
	},
	"life_tap_1": {
		"title": "Life Tap",
		"class_tab": "Warlock",
		"source_id": 1454,
		"rank": 1,
		"training_level": 6,
		"training_cost": 100,
		"mana_cost": 0,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 0,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 16,
		"family": "life_tap",
		"effect": "LIFE_TAP",
		"target": "SELF",
		"minimum": 20,
		"maximum": 20,
		"scaling_rate": 1,
		"coefficient": 0.8,
		"detail": "Converts health to mana; cannot consume your last health point."
	},
	"curse_of_agony_1": {
		"title": "Curse of Agony",
		"class_tab": "Warlock",
		"source_id": 980,
		"rank": 1,
		"training_level": 8,
		"training_cost": 200,
		"mana_cost": 25,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 6,
		"duration": 24,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "curse_of_agony",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"periodic_damage": 7,
		"tick_seconds": 2,
		"coefficient": 0.0,
		"tick_coefficient": 0.055,
		"detail": "84 shadow damage over 24 turns, rising from half to normal to 1.5x ticks. One curse per target."
	},
	"fear_1": {
		"title": "Fear",
		"class_tab": "Warlock",
		"source_id": 5782,
		"rank": 1,
		"training_level": 8,
		"training_cost": 200,
		"mana_cost": 0,
		"mana_percent": 15,
		"cast_seconds": 1.5,
		"range_tiles": 4,
		"duration": 10,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "fear",
		"effect": "FEAR",
		"target": "ENEMY",
		"minimum": 0,
		"maximum": 0,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "One feared enemy flees through legal tiles for up to 10 turns; damage can break fear."
	},
	"demon_skin_2": {
		"title": "Demon Skin",
		"class_tab": "Warlock",
		"source_id": 696,
		"rank": 2,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 120,
		"mana_percent": 0,
		"cast_seconds": 1.0,
		"range_tiles": 0,
		"duration": 1800,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "demon_skin",
		"effect": "ARMOR",
		"target": "SELF",
		"minimum": 120,
		"maximum": 120,
		"scaling_rate": 0,
		"coefficient": 0,
		"prerequisite": "demon_skin_1",
		"detail": "Armor and +3 / +5 health every 5 turns, including combat."
	},
	"summon_voidwalker_1": {
		"title": "Summon Voidwalker",
		"class_tab": "Warlock",
		"source_id": 697,
		"rank": 1,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 0,
		"mana_percent": 100,
		"cast_seconds": 10.0,
		"range_tiles": 0,
		"duration": 0,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "summon_voidwalker",
		"effect": "SUMMON",
		"target": "NONE",
		"minimum": 1,
		"maximum": 1,
		"scaling_rate": 0,
		"coefficient": 0,
		"detail": "Summon one Voidwalker on a free adjacent tile. Torment at pet level 10. Reagents ignored."
	},
	"immolate_2": {
		"title": "Immolate",
		"class_tab": "Warlock",
		"source_id": 707,
		"rank": 2,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 45,
		"mana_percent": 0,
		"cast_seconds": 2.0,
		"range_tiles": 6,
		"duration": 15,
		"school": 2,
		"cooldown_seconds": 0,
		"scaling_max": 15,
		"family": "immolate",
		"effect": "DAMAGE",
		"target": "ENEMY",
		"minimum": 19,
		"maximum": 19,
		"scaling_rate": 0.9,
		"periodic_damage": 8,
		"tick_seconds": 3,
		"coefficient": 0.125,
		"tick_coefficient": 0.125,
		"prerequisite": "immolate_1",
		"detail": ""
	},
	"drain_soul_1": {
		"title": "Drain Soul",
		"class_tab": "Warlock",
		"source_id": 1120,
		"rank": 1,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 55,
		"mana_percent": 0,
		"cast_seconds": 15.0,
		"range_tiles": 6,
		"duration": 15,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "drain_soul",
		"effect": "CHANNEL",
		"target": "ENEMY",
		"minimum": 11,
		"maximum": 11,
		"scaling_rate": 0,
		"tick_seconds": 3,
		"coefficient": 0.0,
		"detail": "Five damage ticks, one every 3 turns. Mana charged once at start; cancellation preserves delivered ticks."
	},
	"healthstone_1": {
		"title": "Create Healthstone (Minor)",
		"class_tab": "Warlock",
		"source_id": 6201,
		"rank": 1,
		"training_level": 10,
		"training_cost": 300,
		"mana_cost": 95,
		"mana_percent": 0,
		"cast_seconds": 3.0,
		"range_tiles": 0,
		"duration": 0,
		"school": 5,
		"cooldown_seconds": 0,
		"scaling_max": 0,
		"family": "healthstone",
		"effect": "CONJURE",
		"target": "NONE",
		"minimum": 1,
		"maximum": 1,
		"scaling_rate": 0,
		"item_id": 5512,
		"coefficient": 0,
		"detail": "Creates one unique Minor Healthstone, restoring 100 health when used. Reagents ignored."
	}
}


static func pet_command(identifier: StringName) -> SkillRank:
	var titles := {&"pet_attack": "Pet: Attack", &"pet_follow": "Pet: Stop / Follow",
		&"pet_dismiss": "Pet: Dismiss"}
	if not titles.has(identifier):
		return null
	var skill := SkillRank.new(identifier, titles[identifier], &"Warlock", 1, 1,
		"Command your active pet. No time passes until a player action.", SkillRank.Effect.PET_COMMAND)
	skill.target = SkillRank.Target.ENEMY if identifier == &"pet_attack" else SkillRank.Target.NONE
	skill.range_tiles = 1000
	return skill
