class_name NorthshireItems
extends RefCounted

## Vanilla item_template values (DATA-004).
const ITEMS: Dictionary = {
	"182": {
		"title": "Garrick's Head",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": true,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "6",
		"tradable": false
	},
	"6076": {
		"title": "Tapered Pants",
		"slot": "legs",
		"level": 0,
		"stack": 1,
		"buy": 47,
		"sell": 9,
		"armor": 9,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"60": {
		"title": "Layered Tunic",
		"slot": "chest",
		"level": 0,
		"stack": 1,
		"buy": 60,
		"sell": 12,
		"armor": 33,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"3070": {
		"title": "Ensign Cloak",
		"slot": "back",
		"level": 0,
		"stack": 1,
		"buy": 55,
		"sell": 11,
		"armor": 5,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"752": {
		"title": "Red Burlap Bandana",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "18",
		"tradable": false
	},
	"2224": {
		"title": "Militia Dagger",
		"slot": "main_hand",
		"level": 0,
		"stack": 1,
		"buy": 122,
		"sell": 24,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 2,
		"maximum": 4,
		"interval": 1.5,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"5580": {
		"title": "Militia Hammer",
		"slot": "main_hand",
		"level": 0,
		"stack": 1,
		"buy": 128,
		"sell": 25,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 3,
		"maximum": 6,
		"interval": 2.3,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1161": {
		"title": "Militia Shortsword",
		"slot": "main_hand",
		"level": 0,
		"stack": 1,
		"buy": 128,
		"sell": 25,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 3,
		"maximum": 7,
		"interval": 2.5,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"5579": {
		"title": "Militia Warhammer",
		"slot": "main_hand",
		"level": 0,
		"stack": 1,
		"buy": 160,
		"sell": 32,
		"armor": 0,
		"two_handed": true,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 6,
		"maximum": 9,
		"interval": 2.9,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1159": {
		"title": "Militia Quarterstaff",
		"slot": "main_hand",
		"level": 0,
		"stack": 1,
		"buy": 160,
		"sell": 32,
		"armor": 0,
		"two_handed": true,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 6,
		"maximum": 9,
		"interval": 2.8,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2186": {
		"title": "Outfitter Belt",
		"slot": "waist",
		"level": 0,
		"stack": 1,
		"buy": 30,
		"sell": 6,
		"armor": 19,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2691": {
		"title": "Outfitter Boots",
		"slot": "feet",
		"level": 0,
		"stack": 1,
		"buy": 54,
		"sell": 10,
		"armor": 46,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"11192": {
		"title": "Outfitter Gloves",
		"slot": "hands",
		"level": 0,
		"stack": 1,
		"buy": 23,
		"sell": 4,
		"armor": 6,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"80": {
		"title": "Soft Fur-lined Shoes",
		"slot": "feet",
		"level": 0,
		"stack": 1,
		"buy": 35,
		"sell": 7,
		"armor": 7,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6070": {
		"title": "Wolfskin Bracers",
		"slot": "wrists",
		"level": 0,
		"stack": 1,
		"buy": 31,
		"sell": 6,
		"armor": 15,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"9571": {
		"title": "Glyphic Letter",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": true,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "3104",
		"tradable": false
	},
	"11119": {
		"title": "Milly's Harvest",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "3904",
		"tradable": false
	},
	"11125": {
		"title": "Grape Manifest",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": true,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "3905",
		"tradable": false
	},
	"11475": {
		"title": "Wine-stained Cloak",
		"slot": "back",
		"level": 0,
		"stack": 1,
		"buy": 38,
		"sell": 7,
		"armor": 5,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2690": {
		"title": "Latched Belt",
		"slot": "waist",
		"level": 0,
		"stack": 1,
		"buy": 38,
		"sell": 7,
		"armor": 38,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2589": {
		"title": "Linen Cloth",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 55,
		"sell": 13,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	}
}
