class_name ClassItems
extends RefCounted

## DATA-001/004 class outfits and Minor Healthstone.
const ITEMS: Dictionary = {
	"6144": {
		"title": "Neophyte's Robe",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"5512": {
		"title": "Minor Healthstone",
		"slot": "",
		"level": 1,
		"stack": 1,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": true,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "healthstone",
		"quest": "",
		"tradable": false,
		"restore_min": 100,
		"restore_max": 100,
		"cooldown": 120
	},
	"35": {
		"title": "Bent Staff",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 47,
		"sell": 9,
		"armor": 0,
		"two_handed": true,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 3,
		"maximum": 5,
		"interval": 2.9,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"36": {
		"title": "Worn Mace",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 38,
		"sell": 7,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 1,
		"maximum": 3,
		"interval": 1.9,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"43": {
		"title": "Squire's Boots",
		"slot": "feet",
		"level": 0,
		"stack": 1,
		"buy": 4,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2092": {
		"title": "Worn Dagger",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 35,
		"sell": 7,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 1,
		"maximum": 2,
		"interval": 1.6,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"44": {
		"title": "Squire's Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 4,
		"sell": 1,
		"armor": 2,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"45": {
		"title": "Squire's Shirt",
		"slot": "shirt",
		"level": 0,
		"stack": 1,
		"buy": 1,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"51": {
		"title": "Neophyte's Boots",
		"slot": "feet",
		"level": 0,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"52": {
		"title": "Neophyte's Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 2,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"53": {
		"title": "Neophyte's Shirt",
		"slot": "shirt",
		"level": 0,
		"stack": 1,
		"buy": 1,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"55": {
		"title": "Apprentice's Boots",
		"slot": "feet",
		"level": 0,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"56": {
		"title": "Apprentice's Robe",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"57": {
		"title": "Acolyte's Robe",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2362": {
		"title": "Worn Wooden Shield",
		"slot": "off_hand",
		"level": 1,
		"stack": 1,
		"buy": 7,
		"sell": 1,
		"armor": 5,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": true,
		"block": 1,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"59": {
		"title": "Acolyte's Shoes",
		"slot": "feet",
		"level": 0,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2361": {
		"title": "Battleworn Hammer",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 45,
		"sell": 9,
		"armor": 0,
		"two_handed": true,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 3,
		"maximum": 5,
		"interval": 2.9,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6096": {
		"title": "Apprentice's Shirt",
		"slot": "shirt",
		"level": 0,
		"stack": 1,
		"buy": 1,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6097": {
		"title": "Acolyte's Shirt",
		"slot": "shirt",
		"level": 0,
		"stack": 1,
		"buy": 1,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6123": {
		"title": "Novice's Robe",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 4,
		"sell": 1,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6124": {
		"title": "Novice's Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 2,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1395": {
		"title": "Apprentice's Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 2,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1396": {
		"title": "Acolyte's Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 4,
		"sell": 1,
		"armor": 2,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6134": {
		"title": "Primitive Mantle",
		"slot": "shirt",
		"level": 0,
		"stack": 1,
		"buy": 1,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6135": {
		"title": "Primitive Kilt",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 14,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"9570": {
		"title": "Consecrated Letter",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "3101",
		"tradable": false
	},
	"9576": {
		"title": "Tainted Letter",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "3105",
		"tradable": false
	},
	"9548": {
		"title": "Hallowed Letter",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "3103",
		"tradable": false
	}
}
