class_name ItemData
extends RefCounted

## Vanilla item values; DATA-004 in docs/data/learning-baseline.md.
const ITEMS: Dictionary = {
	"35": {
		"title": "Bent Staff",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 47,
		"sell": 9,
		"armor": 0,
		"two_handed": true,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 3,
		"maximum": 5,
		"interval": 2.9,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"55": {
		"title": "Apprentice's Boots",
		"slot": "feet",
		"level": 0,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"56": {
		"title": "Apprentice's Robe",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1395": {
		"title": "Apprentice's Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 2,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6096": {
		"title": "Apprentice's Shirt",
		"slot": "shirt",
		"level": 0,
		"stack": 1,
		"buy": 1,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6123": {
		"title": "Novice's Robe",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 4,
		"sell": 1,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6124": {
		"title": "Novice's Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 5,
		"sell": 1,
		"armor": 2,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2139": {
		"title": "Dirk",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 57,
		"sell": 11,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 1,
		"maximum": 3,
		"interval": 1.6,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2129": {
		"title": "Large Round Shield",
		"slot": "off_hand",
		"level": 1,
		"stack": 1,
		"buy": 77,
		"sell": 15,
		"armor": 55,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": true,
		"block": 1,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"85": {
		"title": "Dirty Leather Vest",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 62,
		"sell": 12,
		"armor": 33,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2572": {
		"title": "Red Linen Robe",
		"slot": "chest",
		"level": 5,
		"stack": 1,
		"buy": 496,
		"sell": 99,
		"armor": 19,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {
			"intellect": 1
		},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"6527": {
		"title": "Ancestral Robe",
		"slot": "chest",
		"level": 8,
		"stack": 1,
		"buy": 937,
		"sell": 187,
		"armor": 25,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {
			"intellect": 2,
			"stamina": 1
		},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"117": {
		"title": "Tough Jerky",
		"slot": "",
		"level": 1,
		"stack": 20,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "food",
		"quest": "",
		"tradable": true,
		"restore": 61,
		"duration": 18
	},
	"159": {
		"title": "Refreshing Spring Water",
		"slot": "",
		"level": 1,
		"stack": 20,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "water",
		"quest": "",
		"tradable": true,
		"restore": 151,
		"duration": 18
	},
	"118": {
		"title": "Minor Healing Potion",
		"slot": "",
		"level": 1,
		"stack": 5,
		"buy": 20,
		"sell": 5,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "health",
		"quest": "",
		"tradable": true,
		"restore_min": 70,
		"restore_max": 90,
		"cooldown": 120
	},
	"2455": {
		"title": "Minor Mana Potion",
		"slot": "",
		"level": 5,
		"stack": 5,
		"buy": 40,
		"sell": 10,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "mana",
		"quest": "",
		"tradable": true,
		"restore_min": 140,
		"restore_max": 180,
		"cooldown": 120
	},
	"5349": {
		"title": "Conjured Muffin",
		"slot": "",
		"level": 1,
		"stack": 20,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "food",
		"quest": "",
		"tradable": false,
		"restore": 61,
		"duration": 18
	},
	"5350": {
		"title": "Conjured Water",
		"slot": "",
		"level": 1,
		"stack": 20,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "water",
		"quest": "",
		"tradable": false,
		"restore": 151,
		"duration": 18
	},
	"2288": {
		"title": "Conjured Fresh Water",
		"slot": "",
		"level": 5,
		"stack": 20,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "water",
		"quest": "",
		"tradable": false,
		"restore": 436,
		"duration": 21
	},
	"7073": {
		"title": "Broken Fang",
		"slot": "",
		"level": 0,
		"stack": 5,
		"buy": 25,
		"sell": 6,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"7074": {
		"title": "Chipped Claw",
		"slot": "",
		"level": 0,
		"stack": 5,
		"buy": 16,
		"sell": 4,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"4865": {
		"title": "Ruined Pelt",
		"slot": "",
		"level": 0,
		"stack": 5,
		"buy": 20,
		"sell": 5,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"750": {
		"title": "Tough Wolf Meat",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 0,
		"sell": 0,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "wolves",
		"tradable": false
	},
	"4560": {
		"title": "Fine Scimitar",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 185,
		"sell": 37,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 3,
		"maximum": 6,
		"interval": 1.9,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2950": {
		"title": "Icicle Rod",
		"slot": "main_hand",
		"level": 0,
		"stack": 1,
		"buy": 17384,
		"sell": 3476,
		"armor": 0,
		"two_handed": true,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 51,
		"maximum": 77,
		"interval": 3.8,
		"stats": {
			"intellect": 4
		},
		"use": "",
		"quest": "",
		"tradable": true
	}
}


static func get_item(identifier: int) -> Dictionary:
	return ITEMS.get(str(identifier), {})


static func instance(identifier: int, quantity: int = 1, starter: bool = false) -> Dictionary:
	return {"id": identifier, "quantity": quantity, "starter": starter}


static func describe(identifier: int) -> String:
	var item := get_item(identifier)
	var detail := "%s / level %d / %s / armor %d" % [
		item.title, item.level, item.slot if item.slot != "" else "Item", item.armor]
	if item.weapon:
		detail += " / %.0f–%.0f damage, %.1fs" % [item.minimum, item.maximum, item.interval]
	for stat in item.stats:
		detail += " / +%d %s" % [item.stats[stat], stat]
	if item.two_handed:
		detail += " / two hands"
	if item.use != "":
		detail += " / restores " + String(item.use)
	return detail
