class_name LootItems
extends RefCounted

## Vanilla item_template values; docs/data/loot.md records all source items.
const ITEMS: Dictionary = {
	"755": {
		"title": "Melted Candle",
		"slot": "",
		"level": 0,
		"stack": 5,
		"buy": 4,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"765": {
		"title": "Silverleaf",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 40,
		"sell": 10,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods; professions are outside this demo."
	},
	"805": {
		"title": "Small Red Pouch",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 1000,
		"sell": 250,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods only; inventory capacity is fixed at 40 slots."
	},
	"828": {
		"title": "Small Blue Pouch",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 1000,
		"sell": 250,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods only; inventory capacity is fixed at 40 slots."
	},
	"1364": {
		"title": "Ragged Leather Vest",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 41,
		"sell": 8,
		"armor": 31,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1366": {
		"title": "Ragged Leather Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 11,
		"sell": 2,
		"armor": 17,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1367": {
		"title": "Ragged Leather Boots",
		"slot": "feet",
		"level": 1,
		"stack": 1,
		"buy": 14,
		"sell": 2,
		"armor": 16,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1368": {
		"title": "Ragged Leather Gloves",
		"slot": "hands",
		"level": 1,
		"stack": 1,
		"buy": 14,
		"sell": 2,
		"armor": 17,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1369": {
		"title": "Ragged Leather Belt",
		"slot": "waist",
		"level": 1,
		"stack": 1,
		"buy": 21,
		"sell": 4,
		"armor": 18,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1370": {
		"title": "Ragged Leather Bracers",
		"slot": "wrists",
		"level": 1,
		"stack": 1,
		"buy": 14,
		"sell": 2,
		"armor": 12,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1372": {
		"title": "Ragged Cloak",
		"slot": "back",
		"level": 1,
		"stack": 1,
		"buy": 11,
		"sell": 2,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1374": {
		"title": "Frayed Shoes",
		"slot": "feet",
		"level": 1,
		"stack": 1,
		"buy": 16,
		"sell": 3,
		"armor": 5,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1376": {
		"title": "Frayed Cloak",
		"slot": "back",
		"level": 1,
		"stack": 1,
		"buy": 23,
		"sell": 4,
		"armor": 5,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1377": {
		"title": "Frayed Gloves",
		"slot": "hands",
		"level": 1,
		"stack": 1,
		"buy": 6,
		"sell": 1,
		"armor": 4,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1378": {
		"title": "Frayed Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 9,
		"sell": 1,
		"armor": 4,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"1380": {
		"title": "Frayed Robe",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 21,
		"sell": 4,
		"armor": 8,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2055": {
		"title": "Small Wooden Hammer",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 80,
		"sell": 16,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 2,
		"maximum": 4,
		"interval": 1.9,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2057": {
		"title": "Pitted Defias Shortsword",
		"slot": "main_hand",
		"level": 1,
		"stack": 1,
		"buy": 81,
		"sell": 16,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 2,
		"maximum": 4,
		"interval": 2.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2070": {
		"title": "Darnassian Bleu",
		"slot": "",
		"level": 1,
		"stack": 20,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "food",
		"quest": "",
		"tradable": true,
		"restore": 61,
		"duration": 18
	},
	"2210": {
		"title": "Battered Buckler",
		"slot": "off_hand",
		"level": 1,
		"stack": 1,
		"buy": 15,
		"sell": 3,
		"armor": 12,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": true,
		"block": 1,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2211": {
		"title": "Bent Large Shield",
		"slot": "off_hand",
		"level": 1,
		"stack": 1,
		"buy": 35,
		"sell": 7,
		"armor": 32,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": true,
		"block": 1,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2396": {
		"title": "Light Mail Bracers",
		"slot": "wrists",
		"level": 5,
		"stack": 1,
		"buy": 215,
		"sell": 43,
		"armor": 45,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2398": {
		"title": "Light Chain Armor",
		"slot": "chest",
		"level": 5,
		"stack": 1,
		"buy": 434,
		"sell": 86,
		"armor": 102,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2447": {
		"title": "Peacebloom",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 40,
		"sell": 10,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods; professions are outside this demo."
	},
	"2649": {
		"title": "Flimsy Chain Belt",
		"slot": "waist",
		"level": 1,
		"stack": 1,
		"buy": 7,
		"sell": 1,
		"armor": 24,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2650": {
		"title": "Flimsy Chain Boots",
		"slot": "feet",
		"level": 1,
		"stack": 1,
		"buy": 16,
		"sell": 3,
		"armor": 34,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2651": {
		"title": "Flimsy Chain Bracers",
		"slot": "wrists",
		"level": 1,
		"stack": 1,
		"buy": 16,
		"sell": 3,
		"armor": 25,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2652": {
		"title": "Flimsy Chain Cloak",
		"slot": "back",
		"level": 1,
		"stack": 1,
		"buy": 36,
		"sell": 7,
		"armor": 5,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2653": {
		"title": "Flimsy Chain Gloves",
		"slot": "hands",
		"level": 1,
		"stack": 1,
		"buy": 15,
		"sell": 3,
		"armor": 35,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2654": {
		"title": "Flimsy Chain Pants",
		"slot": "legs",
		"level": 1,
		"stack": 1,
		"buy": 14,
		"sell": 2,
		"armor": 37,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2656": {
		"title": "Flimsy Chain Vest",
		"slot": "chest",
		"level": 1,
		"stack": 1,
		"buy": 48,
		"sell": 9,
		"armor": 63,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"2770": {
		"title": "Copper Ore",
		"slot": "",
		"level": 0,
		"stack": 10,
		"buy": 20,
		"sell": 5,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods; professions are outside this demo."
	},
	"2772": {
		"title": "Iron Ore",
		"slot": "",
		"level": 0,
		"stack": 10,
		"buy": 600,
		"sell": 150,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods; professions are outside this demo."
	},
	"2835": {
		"title": "Rough Stone",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 8,
		"sell": 2,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods; professions are outside this demo."
	},
	"3363": {
		"title": "Frayed Belt",
		"slot": "waist",
		"level": 1,
		"stack": 1,
		"buy": 7,
		"sell": 1,
		"armor": 3,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"3365": {
		"title": "Frayed Bracers",
		"slot": "wrists",
		"level": 1,
		"stack": 1,
		"buy": 16,
		"sell": 3,
		"armor": 4,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"3471": {
		"title": "Copper Chain Vest",
		"slot": "chest",
		"level": 5,
		"stack": 1,
		"buy": 712,
		"sell": 142,
		"armor": 108,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {
			"strength": 1
		},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"4302": {
		"title": "Small Green Dagger",
		"slot": "main_hand",
		"level": 5,
		"stack": 1,
		"buy": 732,
		"sell": 146,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 4,
		"maximum": 9,
		"interval": 1.5,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"4496": {
		"title": "Small Brown Pouch",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 500,
		"sell": 125,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods only; inventory capacity is fixed at 40 slots."
	},
	"4536": {
		"title": "Shiny Red Apple",
		"slot": "",
		"level": 1,
		"stack": 20,
		"buy": 5,
		"sell": 1,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "food",
		"quest": "",
		"tradable": true,
		"restore": 61,
		"duration": 18
	},
	"4766": {
		"title": "Feral Blade",
		"slot": "main_hand",
		"level": 8,
		"stack": 1,
		"buy": 2407,
		"sell": 481,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": true,
		"shield": false,
		"block": 0,
		"minimum": 12,
		"maximum": 24,
		"interval": 2.6,
		"stats": {
			"agility": 1
		},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"5364": {
		"title": "Dry Salt Lick",
		"slot": "",
		"level": 0,
		"stack": 5,
		"buy": 110,
		"sell": 27,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true
	},
	"5498": {
		"title": "Small Lustrous Pearl",
		"slot": "",
		"level": 0,
		"stack": 20,
		"buy": 800,
		"sell": 200,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods; professions are outside this demo."
	},
	"5571": {
		"title": "Small Black Pouch",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 1000,
		"sell": 250,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods only; inventory capacity is fixed at 40 slots."
	},
	"5572": {
		"title": "Small Green Pouch",
		"slot": "",
		"level": 0,
		"stack": 1,
		"buy": 1000,
		"sell": 250,
		"armor": 0,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {},
		"use": "",
		"quest": "",
		"tradable": true,
		"note": "Trade goods only; inventory capacity is fixed at 40 slots."
	},
	"7280": {
		"title": "Rugged Leather Pants",
		"slot": "legs",
		"level": 6,
		"stack": 1,
		"buy": 814,
		"sell": 162,
		"armor": 51,
		"two_handed": false,
		"unique": false,
		"weapon": false,
		"shield": false,
		"block": 0,
		"minimum": 0,
		"maximum": 0,
		"interval": 0.0,
		"stats": {
			"stamina": 1
		},
		"use": "",
		"quest": "",
		"tradable": true
	}
}
